# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2058c601a4656227600a365a3f1e45534f0288eb2662935e354c35e37720f9c2c036ee9dfca713a10a6100db3d7bf89b3895b14823e1291a9b2e4ce0cea843e3

test:
  secret_key_base: 562e8c706242c7d0919333177d37401d9e8de3fb15b66c30cdbfac4bbb87af18880aed6480392ed039e06989a499e1c44c5e7097028b247fc2b05622e44fadcf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
